slogan: "Technical blog for the future me and other beings."

menu:
  - title: Archives
    url: archives
    intro: "All the articles."
    icon: "fa fa-archive"
  - title: Categories
    url: categories
    intro: "All the categories."
    icon: "fa fa-folder"
  - title: Tags
    url: tags
    intro: "All the tags."
    icon: "fa fa-tags"
  - title: About
    url: about
    intro: "About me."
    icon: "fa fa-user"

links:
  - title: "My GitHub"
    url: https://www.github.com/leesei
    intro: "My GitHub account."
    icon: "fa fa-fw fa-github"
  - title: "My Repos Grid"
    url: http://leesei.github.io/repos-grid
    intro: "My repos on GitHub, in grids."
    icon: "fa fa-fw fa-github"
  - title: "My Repos List"
    url: http://leesei.github.io/repos-list
    intro: "My repos on GitHub, in list."
    icon: "fa fa-fw fa-github"
  - title: "Source"
    url: https://github.com/leesei/leesei.github.io/tree/source
    intro: "Source for this blog."
    icon: "fa fa-fw fa-code"
  - title: "RSS"
    url: atom.xml
    intro: "RSS feed"
    icon: "fa fa-fw fa-rss-square"
  - title: "Site Map"
    url: sitemap.xml
    intro: "Sitemap"
    icon: "fa fa-fw fa-sitemap"

widgets:
- search
- category
- tagcloud
# - recent_posts
- links

rss:
fancybox: true
favicon: favicon.png
duoshuo_shortname:

# Analytics
google_analytics:
  enable: false
  siteid:
baidu_tongji:
  enable: false
  siteid:

customize:
  author: leesei
  url: https://github.com/leesei/hexo-theme-freemind/tree/leesei.github.io
